#!/usr/bin/env python3
"""
Skeleton Mirror — Deterministic KO→EN Skeleton Transformation
==============================================================
Transforms Korean skeleton templates into English equivalents using
pure string/regex replacement. No LLM involved — same input always
produces same output.

Design Principle: "계산은 Python이, 판단은 LLM이."
    Skeleton structure is FIXED → Python transforms it deterministically.
    Report CONTENT requires judgment → LLM fills placeholders.

POST-VERIFY invariant: The set of {{PLACEHOLDER}} tokens must be
identical before and after transformation.

Usage (CLI):
    python3 env-scanning/core/skeleton_mirror.py \\
        --input .claude/skills/env-scanner/references/report-skeleton.md \\
        --output .claude/skills/env-scanner/references/report-skeleton-en.md

Usage (importable):
    from core.skeleton_mirror import mirror_skeleton
    en_content, report = mirror_skeleton(ko_content)
"""

import json
import re
import sys
from pathlib import Path
from typing import Dict, List, Set, Tuple

VERSION = "1.0.0"

# ============================================================================
# KO→EN Replacement Table
# ============================================================================
# Organized by category for readability. Sorted by Korean string length
# (descending) at runtime to prevent partial-match corruption.
# Rule: longer/more-specific Korean strings are always replaced first.

_RAW_REPLACEMENTS: List[Tuple[str, str]] = [
    # ---- Meta block titles (top of each skeleton file) ----
    ("# 멀티글로벌 뉴스 환경 스캐닝 보고서 스켈레톤 (WF4 Report Skeleton Template)",
     "# WF4 Report Skeleton Template (Multi&Global-News)"),
    ("# 네이버 뉴스 환경 스캐닝 보고서 스켈레톤 (WF3 Report Skeleton Template)",
     "# WF3 Report Skeleton Template (Naver News)"),
    ("# 통합 보고서 스켈레톤 템플릿 (Integrated Report Skeleton Template)",
     "# Integrated Report Skeleton Template"),
    ("# 주간 보고서 스켈레톤 템플릿 (Weekly Report Skeleton Template)",
     "# Weekly Report Skeleton Template"),
    ("# 보고서 스켈레톤 템플릿 (Report Skeleton Template)",
     "# Report Skeleton Template (Standard/arXiv)"),

    # ---- Meta blockquote lines (purpose, language, notes) ----
    ('> **용도**: report-generator 에이전트가 보고서를 "자유 생성"하지 않고, 이 구조를 **채우는** 방식으로 작성합니다.',
     "> **Purpose**: The report-generator agent fills this structure rather than generating free-form reports."),
    ('> **용도**: report-merger 에이전트가 보고서를 "자유 생성"하지 않고, 이 구조를 **채우는** 방식으로 작성합니다.',
     "> **Purpose**: The report-merger agent fills this structure rather than generating free-form reports."),
    ('> **용도**: 주간 메타분석 보고서를 "자유 생성"하지 않고, 이 구조를 **채우는** 방식으로 작성합니다.',
     "> **Purpose**: Weekly meta-analysis reports are generated by filling this structure, not free-form."),
    ("> 모든 `{{PLACEHOLDER}}` 토큰은 반드시 실제 내용으로 대체되어야 합니다.",
     "> All `{{PLACEHOLDER}}` tokens must be replaced with actual content."),
    ("> 미채워진 플레이스홀더가 남으면 **SKEL-001 검증 실패**가 발생합니다.",
     "> Unfilled placeholders will trigger **SKEL-001 validation failure**."),
    ("> **작성 언어**: 한국어 (기술 용어, 고유명사, 약어는 영문 병기 허용)",
     "> **Language**: English (technical terms and acronyms preserved as-is)"),
    ("> **WF3 전용**: 이 스켈레톤은 네이버 뉴스 환경스캐닝(WF3) 전용입니다.",
     "> **WF3 Only**: This skeleton is exclusively for Naver News environmental scanning (WF3)."),
    ("> WF1/WF2 보고서에는 `report-skeleton.md`를, 통합 보고서에는 `integrated-report-skeleton.md`를 사용하세요.",
     "> For WF1/WF2 reports use `report-skeleton.md`; for integrated reports use `integrated-report-skeleton.md`."),
    ("> **WF3 특화 섹션**: FSSF 8-type 분류, Three Horizons 분포, 전환점(Tipping Point) 경고, 이상 탐지 결과",
     "> **WF3-specific sections**: FSSF 8-type classification, Three Horizons distribution, Tipping Point alerts, anomaly detection"),
    ("> **검증 프로파일**: `naver` (validate_report.py --profile naver)",
     "> **Validation profile**: `naver` (validate_report.py --profile naver)"),
    ("> **검증 프로파일**: `weekly` (validate_report.py --profile weekly)",
     "> **Validation profile**: `weekly` (validate_report.py --profile weekly)"),
    ("> **중요**: 이 스켈레톤은 WF1(일반), WF2(arXiv), WF3(네이버 뉴스) 세 독립 워크플로우의 결과를",
     "> **Important**: This skeleton integrates results from three independent workflows:"),
    ("> 통합한 보고서용입니다. 개별 워크플로우 보고서에는 `report-skeleton.md`(WF1/WF2) 또는 `naver-report-skeleton.md`(WF3)를 사용하세요.",
     "> WF1 (General), WF2 (arXiv), WF3 (Naver News). For individual reports, use `report-skeleton.md` or `naver-report-skeleton.md`."),
    ("> **중요**: 이 스켈레톤은 7일간의 일일 스캔 결과를 거시적으로 재분석한",
     "> **Important**: This skeleton is for weekly meta-analysis of 7 days of daily scan results."),
    ("> 주간 메타분석 보고서용입니다. 일일 보고서에는 `report-skeleton.md`를,",
     "> For daily reports use `report-skeleton.md`;"),
    ("> 통합 일일 보고서에는 `integrated-report-skeleton.md`를 사용하세요.",
     "> for integrated daily reports use `integrated-report-skeleton.md`."),

    # ---- Usage instruction block ----
    ("## 사용 지침", "## Usage Instructions"),
    ("1. 이 템플릿을 복사하여 `integrated/weekly/reports/weekly-scan-{week_id}.md`로 저장합니다.",
     "1. Copy this template to `integrated/weekly/reports/weekly-scan-{week_id}.md`."),
    ("1. 이 템플릿을 복사하여 `integrated/reports/daily/integrated-scan-{date}.md`로 저장합니다.",
     "1. Copy this template to `integrated/reports/daily/integrated-scan-{date}.md`."),
    ("1. 이 템플릿을 복사하여 `reports/daily/environmental-scan-{date}.md`로 저장합니다.",
     "1. Copy this template to `reports/daily/environmental-scan-{date}.md`."),
    ("2. 모든 `{{...}}` 플레이스홀더를 데이터에 기반한 실제 내용으로 대체합니다.",
     "2. Replace all `{{...}}` placeholders with data-driven content."),
    ("3. 섹션 헤더(`## N. ...`)는 **절대 변경하지 마세요** — 정확한 문자열이 검증 대상입니다.",
     "3. Section headers (`## N. ...`) must **never be modified** — exact strings are validated."),
    ("4. 서브섹션 헤더(`### N.N ...`)도 번호를 유지하세요.",
     "4. Subsection headers (`### N.N ...`) must retain their numbering."),
    ("5. 모든 신호에 `[WF1]`, `[WF2]`, 또는 `[WF3]` 소스 태그를 반드시 포함하세요.",
     "5. All signals must include `[WF1]`, `[WF2]`, or `[WF3]` source tags."),
    ("5. 모든 신호/추세에 `[WF1]` 또는 `[WF2]` 소스 태그를 반드시 포함하세요.",
     "5. All signals/trends must include `[WF1]` or `[WF2]` source tags."),
    ("6. 생성 완료 후, 파일에 `{{`가 남아 있지 않은지 확인합니다.",
     "6. After generation, verify no `{{` tokens remain in the file."),
    ("5. 생성 완료 후, 파일에 `{{`가 남아 있지 않은지 확인합니다.",
     "5. After generation, verify no `{{` tokens remain in the file."),

    # ---- Report titles ----
    ("# 통합 일일 환경 스캐닝 보고서", "# Integrated Daily Environmental Scanning Report"),
    ("# 일일 멀티글로벌 뉴스 환경 스캐닝 보고서", "# Daily Multi&Global-News Environmental Scanning Report"),
    ("# 일일 네이버 뉴스 환경 스캐닝 보고서", "# Daily Naver News Environmental Scanning Report"),
    ("# 일일 환경 스캐닝 보고서", "# Daily Environmental Scanning Report"),
    ("# 주간 환경 스캐닝 보고서", "# Weekly Environmental Scanning Report"),

    # ---- Blockquote report metadata lines ----
    ("> **보고서 유형**: WF4 멀티글로벌 뉴스 환경스캐닝 (FSSF + Three Horizons + Tipping Point)",
     "> **Report Type**: WF4 Multi&Global-News Environmental Scanning (FSSF + Three Horizons + Tipping Point)"),
    ("> **보고서 유형**: WF3 네이버 뉴스 환경스캐닝 (FSSF + Three Horizons + Tipping Point)",
     "> **Report Type**: WF3 Naver News Environmental Scanning (FSSF + Three Horizons + Tipping Point)"),
    ("> **보고서 유형**: 통합 보고서 (WF1 일반 환경스캐닝 + WF2 arXiv 학술 심층스캐닝 + WF3 네이버 뉴스 환경스캐닝)",
     "> **Report Type**: Integrated Report (WF1 General + WF2 arXiv Academic + WF3 Naver News)"),
    ("> **보고서 유형**: 주간 메타분석 보고서 (Weekly Meta-Analysis)",
     "> **Report Type**: Weekly Meta-Analysis Report"),
    ("**스캔 시간 범위**:", "**Scan Window**:"),
    ("**기준 시점 (T₀)**:", "**Anchor Time (T\u2080)**:"),
    ("**개별 스캔 범위**:", "**Per-Workflow Scan Range**:"),
    ("**분석 기간**:", "**Analysis Period**:"),
    ("**주간 ID**:", "**Week ID**:"),
    ("**일일 스캔 기준**: 각 일일 스캔은 T₀ 기준", "**Daily Scan Basis**: Each daily scan covers T\u2080-anchored"),

    # ---- Section 3 evolution blockquote labels ----
    ("활성 추적 스레드:", "Active tracking threads:"),
    ("주간 활성 스레드:", "Weekly active threads:"),

    # ---- Section headers (## N.) ----
    ("## 1. 경영진 요약", "## 1. Executive Summary"),
    ("## 2. 신규 탐지 신호", "## 2. Newly Detected Signals"),
    ("## 2. 주간 추세 분석", "## 2. Weekly Trend Analysis"),
    ("## 3. 기존 신호 업데이트", "## 3. Existing Signal Updates"),
    ("## 3. 신호 수렴 분석", "## 3. Signal Convergence Analysis"),
    ("## 4. 패턴 및 연결고리", "## 4. Patterns and Connections"),
    ("## 4. 신호 진화 타임라인", "## 4. Signal Evolution Timeline"),
    ("## 5. 전략적 시사점", "## 5. Strategic Implications"),
    ("## 6. Plausible Scenarios(개연성 있는 시나리오)", "## 6. Plausible Scenarios"),
    ("## 7. 신뢰도 분석", "## 7. Confidence Analysis"),
    ("## 8. 부록", "## 8. Appendix"),
    ("## 8. 시스템 성능 리뷰", "## 8. System Performance Review"),
    ("## 9. 부록", "## 9. Appendix"),

    # ---- Subsection headers (### N.N) — Executive Summary ----
    ("### 오늘의 핵심 발견 (Top 5 신호)", "### Today's Key Findings (Top 5 Signals)"),
    ("### 오늘의 핵심 발견 (Top 3 신호)", "### Today's Key Findings (Top 3 Signals)"),
    ("### 금주의 3대 핵심 추세", "### This Week's Top 3 Key Trends"),
    ("### 주요 변화 요약", "### Key Changes Summary"),
    ("### 주간 신호 통계 요약", "### Weekly Signal Statistics Summary"),
    ("### FSSF 분류 요약", "### FSSF Classification Summary"),
    ("### Three Horizons 분포", "### Three Horizons Distribution"),
    ("### 전환점(Tipping Point) 경고 요약", "### Tipping Point Alert Summary"),
    ("### 워크플로우 교차 하이라이트", "### Cross-Workflow Highlights"),

    # ---- Subsection headers — Section 2 (Weekly) ----
    ("### 2.1 STEEPs별 주간 동향", "### 2.1 STEEPs Weekly Trends"),
    ("### 2.2 상승 추세 (Accelerating)", "### 2.2 Accelerating Trends"),
    ("### 2.3 하락 추세 (Decelerating)", "### 2.3 Decelerating Trends"),
    ("### 2.4 신규 등장 (Newly Emerged)", "### 2.4 Newly Emerged"),
    ("### 2.5 소멸/해소 (Faded)", "### 2.5 Faded/Resolved"),

    # ---- Subsection headers — Section 3 ----
    ("### 3.1 강화 추세 (Strengthening)", "### 3.1 Strengthening Trends"),
    ("### 3.2 약화 추세 (Weakening)", "### 3.2 Weakening Trends"),
    ("### 3.3 신호 상태 요약", "### 3.3 Signal Status Summary"),
    ("### 3.1 수렴 클러스터 (Converging Clusters)", "### 3.1 Converging Clusters"),
    ("### 3.2 발산 신호 (Diverging Signals)", "### 3.2 Diverging Signals"),
    ("### 3.3 WF1↔WF2 교차 검증", "### 3.3 WF1\u2194WF2 Cross-Validation"),

    # ---- Subsection headers — Section 4 ----
    ("### 4.1 신호 간 교차 영향", "### 4.1 Cross-Impact Between Signals"),
    ("### 4.2 떠오르는 테마", "### 4.2 Emerging Themes"),
    ("### 4.3 워크플로우 교차 분석 (Cross-Workflow Analysis)", "### 4.3 Cross-Workflow Analysis"),
    ("### 4.3 FSSF 신호 분류 분포", "### 4.3 FSSF Signal Classification Distribution"),
    ("### 4.4 Three Horizons 분포", "### 4.4 Three Horizons Distribution"),
    ("### 4.5 전환점(Tipping Point) 경고", "### 4.5 Tipping Point Alerts"),
    ("### 4.6 이상 탐지 결과", "### 4.6 Anomaly Detection Results"),
    ("### 4.1 주간 신호 진화 흐름", "### 4.1 Weekly Signal Evolution Flow"),
    ("### 4.2 pSST 점수 변동 추적", "### 4.2 pSST Score Change Tracking"),
    ("### 4.3 신호 성숙도 변화", "### 4.3 Signal Maturity Changes"),

    # ---- Subsection headers — Section 5 ----
    ("### 5.1 즉시 조치 필요 (0-6개월)", "### 5.1 Immediate Actions Required (0-6 months)"),
    ("### 5.2 중기 모니터링 (6-18개월)", "### 5.2 Medium-term Monitoring (6-18 months)"),
    ("### 5.3 모니터링 강화 필요 영역", "### 5.3 Areas Requiring Enhanced Monitoring"),
    ("### 5.3 장기 관찰 필요 (18개월+)", "### 5.3 Long-term Observation (18+ months)"),
    ("### 5.4 이전 주 대비 변화", "### 5.4 Week-over-Week Changes"),

    # ---- Subsection headers — Section 7 (Integrated) ----
    ("### 7.1 통합 pSST 등급 분포", "### 7.1 Unified pSST Grade Distribution"),
    ("### 7.2 워크플로우별 pSST 비교", "### 7.2 Per-Workflow pSST Comparison"),
    ("### 7.3 자동 승인 가능 목록 (Grade A)", "### 7.3 Auto-Approvable List (Grade A)"),
    ("### 7.4 검토 필요 목록 (Grade C/D)", "### 7.4 Review Required List (Grade C/D)"),
    ("### 7.5 차원별 평균 분석", "### 7.5 Per-Dimension Average Analysis"),

    # ---- Subsection headers — Section 7 (Weekly) ----
    ("### 7.1 주간 pSST 등급 분포 추이", "### 7.1 Weekly pSST Grade Distribution Trend"),
    ("### 7.2 소스별 신뢰도 주간 평균", "### 7.2 Source Reliability Weekly Average"),
    ("### 7.3 STEEPs별 평균 pSST 변동", "### 7.3 STEEPs Average pSST Changes"),

    # ---- Subsection headers — Section 8 / 9 (Appendix) ----
    # ---- WF4-specific meta blockquote lines ----
    ("> **WF4 전용**: 이 스켈레톤은 멀티글로벌 뉴스 환경스캐닝(WF4) 전용입니다.",
     "> **WF4 Only**: This skeleton is exclusively for Multi&Global-News environmental scanning (WF4)."),
    ("> WF1/WF2 보고서에는 `report-skeleton.md`를, WF3 보고서에는 `naver-report-skeleton.md`를, 통합 보고서에는 `integrated-report-skeleton.md`를 사용하세요.",
     "> For WF1/WF2 reports use `report-skeleton.md`; for WF3 use `naver-report-skeleton.md`; for integrated use `integrated-report-skeleton.md`."),
    ("> **WF4 특화 섹션**: FSSF 8-type 분류, Three Horizons 분포, 전환점(Tipping Point) 경고, 이상 탐지 결과, 다국어 크롤링 통계, 번역 통계, 차단 대응 기록",
     "> **WF4-specific sections**: FSSF 8-type classification, Three Horizons distribution, Tipping Point alerts, anomaly detection, multilingual crawling statistics, translation statistics, defense log"),
    ("> **검증 프로파일**: `multiglobal-news` (validate_report.py --profile multiglobal-news)",
     "> **Validation profile**: `multiglobal-news` (validate_report.py --profile multiglobal-news)"),

    # ---- WF4-specific executive summary labels ----
    ("### 크롤링 통계 요약", "### Crawling Statistics Summary"),
    ("크롤링 사이트:", "Crawled sites:"),
    ("사이트,", "sites,"),
    ("성공,", "succeeded,"),
    ("실패", "failed"),
    ("번역:", "Translation:"),
    ("언어별 분포:", "Language breakdown:"),
    ("한국어,", "Korean,"),
    ("영어,", "English,"),
    ("중국어,", "Chinese,"),
    ("일본어,", "Japanese,"),
    ("독일어,", "German,"),
    ("프랑스어,", "French,"),
    ("러시아어,", "Russian,"),
    ("기타", "Other"),
    ("건 번역,", " translated,"),
    ("건 실패", " failed"),

    # ---- WF4-specific appendix table headers ----
    ("| 사이트 | 언어 | 기사 수 | 전략 | 성공률 |",
     "| Site | Language | Articles | Strategy | Success Rate |"),
    ("| 총 크롤링 사이트 |", "| Total Sites Crawled |"),
    ("| 성공 사이트 |", "| Sites Succeeded |"),
    ("| 실패 사이트 |", "| Sites Failed |"),
    ("| 언어 | 전체 | 번역 완료 | 실패 | 평균 신뢰도 |",
     "| Language | Total | Translated | Failed | Avg Confidence |"),
    ("| 총 번역 건수 |", "| Total Translated |"),
    ("| 번역 실패 건수 |", "| Translation Failed |"),
    ("| 언어별 — 한국어 |", "| Language — Korean |"),
    ("| 언어별 — 영어 |", "| Language — English |"),
    ("| 언어별 — 중국어 |", "| Language — Chinese |"),
    ("| 언어별 — 일본어 |", "| Language — Japanese |"),
    ("| 언어별 — 독일어 |", "| Language — German |"),
    ("| 언어별 — 프랑스어 |", "| Language — French |"),
    ("| 언어별 — 러시아어 |", "| Language — Russian |"),
    ("| 언어별 — 기타 |", "| Language — Other |"),
    ("| 차단 유형 | 횟수 | 사용 전략 | 성공률 |",
     "| Block Type | Count | Strategy Used | Success Rate |"),
    ("### 8.4 FSSF 분류 방법론", "### 8.4 FSSF Classification Methodology"),
    ("### 8.5 전체 신호 목록", "### 8.5 Full Signal List"),
    ("### 8.6 출처 목록", "### 8.6 Source List"),

    # ---- existing WF3/WF4 shared appendix headers ----
    ("### 8.2 번역 통계", "### 8.2 Translation Statistics"),
    ("### 8.3 차단 대응 기록", "### 8.3 Defense Log Summary"),
    ("### 8.1 크롤링 통계", "### 8.1 Crawling Statistics"),
    ("### 8.2 FSSF 분류 방법론", "### 8.2 FSSF Classification Methodology"),
    ("### 8.3 전체 신호 목록", "### 8.3 Full Signal List"),
    ("### 8.4 출처 목록", "### 8.4 Source List"),
    ("### 8.1 전체 신호 목록", "### 8.1 Full Signal List"),
    ("### 8.2 출처 목록", "### 8.2 Source List"),
    ("### 8.3 방법론", "### 8.3 Methodology"),
    ("### 8.4 워크플로우 실행 요약", "### 8.4 Workflow Execution Summary"),
    ("### 8.1 주간 스캐닝 품질 지표", "### 8.1 Weekly Scanning Quality Metrics"),
    ("### 8.2 소스 건강 현황", "### 8.2 Source Health Status"),
    ("### 8.3 캘리브레이션 권고", "### 8.3 Calibration Recommendations"),
    ("### 9.1 분석 대상 일일 보고서 목록", "### 9.1 Daily Reports Analyzed"),
    ("### 9.2 주간 전체 추세 목록", "### 9.2 Full Weekly Trend List"),
    ("### 9.3 방법론", "### 9.3 Methodology"),
    ("### 9.4 실행 요약", "### 9.4 Execution Summary"),

    # ---- Sub-subsection headers (####) — Integrated Section 4.3 ----
    ("#### 상호 강화 신호 (Reinforced Signals)", "#### Reinforced Signals"),
    ("#### 학술 선행 신호 (Academic Early Signals)", "#### Academic Early Signals"),
    ("#### 미디어 선행 신호 (Media-First Signals)", "#### Media-First Signals"),
    ("#### 워크플로우 간 긴장/모순 (Cross-Workflow Tensions)", "#### Cross-Workflow Tensions"),
    ("#### WF3 고유 신호 (Naver-Exclusive Signals)", "#### Naver-Exclusive Signals"),
    ("#### 시간축 교차 확인 (Temporal Cross-Validation)", "#### Temporal Cross-Validation"),

    # ---- Signal field labels (9-field format, **bold**) ----
    ("**분류**:", "**Classification**:"),
    ("**출처**:", "**Source**:"),
    ("**핵심 사실**:", "**Key Facts**:"),
    ("**정량 지표**:", "**Quantitative Metrics**:"),
    ("**영향도**:", "**Impact**:"),
    ("**상세 설명**:", "**Detailed Description**:"),
    ("**추론**:", "**Inference**:"),
    ("**이해관계자**:", "**Stakeholders**:"),
    ("**모니터링 지표**:", "**Monitoring Indicators**:"),
    ("**출처 언어**:", "**Source Language**:"),

    # ---- Bullet labels (- **bold**: format) ----
    ("**신뢰도**:", "**Confidence**:"),
    ("**FSSF 유형**:", "**FSSF Type**:"),
    ("**시간 지평**:", "**Time Horizon**:"),
    ("**불확실성**:", "**Uncertainty**:"),
    ("**원본 워크플로우**:", "**Origin Workflow**:"),

    # ---- Inline labels (- label: format in exec summary) ----
    ("- 추세 강도(TIS):", "- Trend Intensity Score (TIS):"),
    ("- 전략적 시사점:", "- Strategic Implications:"),
    ("- 핵심 내용:", "- Key Content:"),
    ("- 중요도:", "- Importance:"),
    ("- FSSF 유형:", "- FSSF Type:"),
    ("- 시간 지평:", "- Time Horizon:"),

    # ---- Integrated report bullet labels ----
    ("- **WF1 (일반 환경스캐닝)**:", "- **WF1 (General Environmental Scanning)**:"),
    ("- **WF2 (arXiv 학술 심층)**:", "- **WF2 (arXiv Academic Deep Scan)**:"),
    ("- **WF3 (네이버 뉴스)**:", "- **WF3 (Naver News)**:"),
    ("- **WF4 (멀티글로벌 뉴스)**:", "- **WF4 (Multi&Global-News)**:"),
    ("- **통합 신호 풀**:", "- **Integrated Signal Pool**:"),
    ("- **상위 20개 신호 선정** (pSST 통합 순위 기준)", "- **Top 20 Signals Selected** (by unified pSST ranking)"),

    # ---- Weekly report bullet labels ----
    ("- **분석 일일 스캔 수**:", "- **Daily Scans Analyzed**:"),
    ("- **분석 대상 총 신호**:", "- **Total Signals Analyzed**:"),
    ("- **상승 추세**:", "- **Accelerating Trends**:"),
    ("- **하락 추세**:", "- **Decelerating Trends**:"),
    ("- **신규 등장**:", "- **Newly Emerged**:"),
    ("- **소멸/해소**:", "- **Faded/Resolved**:"),
    ("- **수렴 클러스터**:", "- **Convergence Clusters**:"),
    ("  - WF1 (일반):", "  - WF1 (General):"),
    ("  - WF2 (arXiv):", "  - WF2 (arXiv):"),

    # ---- Standard report bullets ----
    ("- 발견된 신규 신호:", "- New signals detected:"),
    ("- 우선순위 상위 신호:", "- Top priority signals:"),
    ("- 주요 영향 도메인:", "- Major impact domains:"),

    # ---- Table header rows and cells ----
    # Evolution status table (shared across standard/naver/integrated)
    ("| 상태 | 수 | 비율 |", "| Status | Count | Ratio |"),
    ("| 반복 등장 |", "| Recurring |"),
    ("| 신규 |", "| New |"),
    ("| 강화 |", "| Strengthening |"),
    ("| 약화 |", "| Weakening |"),
    ("| 소멸 |", "| Faded |"),

    # Naver FSSF table cells
    ("| FSSF 유형 | 신호 수 | 대표 신호 | 주요 특징 |",
     "| FSSF Type | Signal Count | Representative Signal | Key Features |"),
    ("| FSSF 유형 | 신호 수 | 비율 |", "| FSSF Type | Signal Count | Ratio |"),
    ("| Weak Signal (약신호) |", "| Weak Signal |"),
    ("| Emerging Issue (부상 이슈) |", "| Emerging Issue |"),
    ("| Trend (추세) |", "| Trend |"),
    ("| Megatrend (메가트렌드) |", "| Megatrend |"),
    ("| Driver (동인) |", "| Driver |"),
    ("| Wild Card (와일드카드) |", "| Wild Card |"),
    ("| Discontinuity (단절) |", "| Discontinuity |"),
    ("| Precursor Event (전조 사건) |", "| Precursor Event |"),

    # Naver Three Horizons table
    ("| 시간 지평 | 신호 수 | 비율 | 설명 |", "| Time Horizon | Signal Count | Ratio | Description |"),
    ("| 시간 지평 | 신호 목록 | 주요 테마 |", "| Time Horizon | Signal List | Key Themes |"),
    ("| 현재 체제 내 변화 |", "| Changes within current regime |"),
    ("| 전환기 신호 |", "| Transitional signals |"),
    ("| 미래 체제 맹아 |", "| Seeds of future regime |"),
    ("(0-2년)", "(0-2 years)"),
    ("(2-7년)", "(2-7 years)"),
    ("(7년+)", "(7+ years)"),

    # Naver Tipping Point / Anomaly tables
    ("| 경고 수준 | 신호 수 | 핵심 신호 |", "| Alert Level | Signal Count | Key Signal |"),
    ("| 경고 레벨 | 신호 | 지표 | 근거 |", "| Alert Level | Signal | Indicator | Evidence |"),
    ("| 유형 | 신호 | 이상 지표 | 심각도 |", "| Type | Signal | Anomaly Indicator | Severity |"),

    # Naver appendix crawling stats table
    ("| 항목 | 값 |", "| Item | Value |"),
    ("| 크롤링 일시 |", "| Crawling Datetime |"),
    ("| 총 수집 기사 |", "| Total Articles Collected |"),
    ("| 정치 |", "| Politics |"),
    ("| 경제 |", "| Economy |"),
    ("| 사회 |", "| Society |"),
    ("| 생활문화 |", "| Life/Culture |"),
    ("| 세계 |", "| World |"),
    ("| IT과학 |", "| IT/Science |"),
    ("| CrawlDefender 전략 |", "| CrawlDefender Strategy |"),

    # Integrated appendix execution summary table
    ("| 항목 | WF1 (일반) | WF2 (arXiv) | WF3 (네이버) | WF4 (멀티글로벌) | 통합 |",
     "| Item | WF1 (General) | WF2 (arXiv) | WF3 (Naver) | WF4 (Multi&Global) | Integrated |"),
    ("| 항목 | WF1 (일반) | WF2 (arXiv) | WF3 (네이버) | 통합 |",
     "| Item | WF1 (General) | WF2 (arXiv) | WF3 (Naver) | Integrated |"),
    ("| 소스 수 |", "| Source Count |"),
    ("| 수집 신호 |", "| Collected Signals |"),
    ("| 중복 제거 후 |", "| After Dedup |"),
    ("| 상위 신호 |", "| Top Signals |"),
    ("| 평균 pSST |", "| Avg pSST |"),
    ("| 실행 시간 |", "| Execution Time |"),
    ("1 (NaverNews)", "1 (NaverNews)"),

    # Weekly appendix execution summary table
    ("| 주간 ID |", "| Week ID |"),
    ("| 분석 기간 |", "| Analysis Period |"),
    ("| 일일 스캔 수 |", "| Daily Scan Count |"),
    ("| 분석 신호 수 |", "| Signals Analyzed |"),
    ("| 수렴 클러스터 |", "| Convergence Clusters |"),
    ("| 핵심 추세 |", "| Key Trends |"),

    # Blockquote evolution pipe separators
    ("| 강화:", "| Strengthening:"),
    ("| 약화:", "| Weakening:"),
    ("| 소멸:", "| Faded:"),
    ("| 신규:", "| New:"),

    # ---- Remaining inline Korean text ----
    ("신호 수집", "signals collected"),
    ("개 신호 선정", " signals selected"),
]

# ============================================================================
# Regex Patterns (applied AFTER string replacements)
# ============================================================================

_REGEX_PATTERNS: List[Tuple[str, str]] = [
    # Signal block headers (### 우선순위 N: / ### 통합 우선순위 N:)
    (r"### 통합 우선순위 (\d+):", r"### Integrated Priority \1:"),
    (r"### 우선순위 (\d+):", r"### Priority \1:"),
    # Counter suffixes after {{PLACEHOLDER}} tokens
    (r"\}\}개", "}}"),
    (r"\}\}시간 범위", "}} hours range"),
    (r"\}\}시간", "}} hours"),
    (r"\}\}일\b", "}} days"),
]

# ============================================================================
# Sort replacements by Korean string length (descending) at module load
# ============================================================================

_SORTED_REPLACEMENTS = sorted(
    _RAW_REPLACEMENTS,
    key=lambda pair: len(pair[0]),
    reverse=True,
)


# ============================================================================
# Core Functions
# ============================================================================

def extract_placeholders(content: str) -> Set[str]:
    """Extract all {{PLACEHOLDER}} token names from content."""
    return set(re.findall(r"\{\{([A-Z0-9_]+)\}\}", content))


def mirror_skeleton(ko_content: str) -> Tuple[str, Dict]:
    """
    Transform Korean skeleton content to English deterministically.

    Args:
        ko_content: Korean skeleton template content

    Returns:
        Tuple of (english_content, transformation_report)
    """
    # PRE-VERIFY: capture placeholder set before transformation
    placeholders_before = extract_placeholders(ko_content)

    content = ko_content

    # Phase 1: Ordered string replacements (longest/most-specific first)
    for ko, en in _SORTED_REPLACEMENTS:
        content = content.replace(ko, en)

    # Phase 2: Regex pattern replacements
    for pattern, replacement in _REGEX_PATTERNS:
        content = re.sub(pattern, replacement, content)

    # POST-VERIFY: placeholder set must be identical
    placeholders_after = extract_placeholders(content)
    missing = placeholders_before - placeholders_after
    added = placeholders_after - placeholders_before

    report = {
        "module": "skeleton_mirror",
        "version": VERSION,
        "placeholders_before": len(placeholders_before),
        "placeholders_after": len(placeholders_after),
        "placeholders_missing": sorted(missing),
        "placeholders_added": sorted(added),
        "placeholder_integrity": not missing and not added,
        "status": "SUCCESS" if (not missing and not added) else "FAIL_PLACEHOLDER_MISMATCH",
    }

    return content, report


def mirror_skeleton_file(
    input_path: str,
    output_path: str,
) -> Tuple[str, Dict]:
    """
    Read Korean skeleton file, transform to English, write output.

    Args:
        input_path: Path to Korean skeleton template
        output_path: Path to write English skeleton

    Returns:
        Tuple of (english_content, transformation_report)
    """
    in_p = Path(input_path)
    if not in_p.exists():
        raise FileNotFoundError(f"Input skeleton not found: {input_path}")

    ko_content = in_p.read_text(encoding="utf-8")
    en_content, report = mirror_skeleton(ko_content)

    out_p = Path(output_path)
    out_p.parent.mkdir(parents=True, exist_ok=True)
    out_p.write_text(en_content, encoding="utf-8")

    report["input"] = str(input_path)
    report["output"] = str(output_path)
    return en_content, report


def mirror_all_skeletons(references_dir: str) -> List[Dict]:
    """
    Transform all 4 Korean skeletons to English counterparts.

    Args:
        references_dir: Path to .claude/skills/env-scanner/references/

    Returns:
        List of transformation reports (one per skeleton)
    """
    ref = Path(references_dir)
    skeleton_pairs = [
        ("report-skeleton.md", "report-skeleton-en.md"),
        ("naver-report-skeleton.md", "naver-report-skeleton-en.md"),
        ("multiglobal-news-report-skeleton.md", "multiglobal-news-report-skeleton-en.md"),
        ("integrated-report-skeleton.md", "integrated-report-skeleton-en.md"),
        ("weekly-report-skeleton.md", "weekly-report-skeleton-en.md"),
    ]

    reports = []
    for ko_name, en_name in skeleton_pairs:
        ko_path = ref / ko_name
        en_path = ref / en_name
        if ko_path.exists():
            _, report = mirror_skeleton_file(str(ko_path), str(en_path))
            reports.append(report)
        else:
            reports.append({
                "input": str(ko_path),
                "status": "SKIP_NOT_FOUND",
            })

    return reports


# ============================================================================
# CLI Entrypoint
# ============================================================================

def main():
    import argparse
    parser = argparse.ArgumentParser(
        description="Skeleton Mirror: deterministic KO\u2192EN skeleton transformation"
    )
    parser.add_argument("--input", help="Korean skeleton file path")
    parser.add_argument("--output", help="English skeleton output path")
    parser.add_argument("--all", dest="transform_all", action="store_true",
                        help="Transform all 4 skeletons (uses --references-dir)")
    parser.add_argument("--references-dir",
                        default=".claude/skills/env-scanner/references",
                        help="References directory (for --all mode)")
    parser.add_argument("--json", action="store_true", dest="json_output",
                        help="Output report as JSON")
    args = parser.parse_args()

    try:
        if args.transform_all:
            reports = mirror_all_skeletons(args.references_dir)
            if args.json_output:
                print(json.dumps(reports, indent=2, ensure_ascii=False))
            else:
                for r in reports:
                    icon = "\u2705" if r.get("status") == "SUCCESS" else "\u274c"
                    print(f"{icon} {r.get('status', 'UNKNOWN')}: "
                          f"{r.get('input', '?')} \u2192 {r.get('output', '?')}")
            failed = [r for r in reports if r.get("status") not in ("SUCCESS", "SKIP_NOT_FOUND")]
            sys.exit(1 if failed else 0)

        elif args.input and args.output:
            _, report = mirror_skeleton_file(args.input, args.output)
            if args.json_output:
                print(json.dumps(report, indent=2, ensure_ascii=False))
            else:
                icon = "\u2705" if report["status"] == "SUCCESS" else "\u274c"
                print(f"{icon} {report['status']}: {report['input']} \u2192 {report['output']}")
                print(f"   Placeholders: {report['placeholders_before']} \u2192 {report['placeholders_after']}")
                if report["placeholders_missing"]:
                    print(f"   Missing: {report['placeholders_missing']}")
            sys.exit(0 if report["status"] == "SUCCESS" else 1)

        else:
            parser.error("Provide --input/--output or --all")

    except Exception as e:
        print(f"ERROR: {e}", file=sys.stderr)
        sys.exit(1)


if __name__ == "__main__":
    main()
